### ISSUE TITLE
Mapping of `vegetatie-ontwikkeling` sheet

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#13]
This sheet link ONE `deelmonster_id` to MANY `interval` values and their related vegetation development.

My proposal, as implemented in the mapping, is the following:
- `eventID`: combination of `deelmonster_id` and `interval`. Examples: `21327837:0-10m`, `21327837:10-20m`.
- `parentEventID`: `deelmonster_id` for those values present in `kenmerken` sheet (97% of the rows). The rows with `deelmonster_id` not in `kenmerken` (and also not present `opnames_lijst` and any other sheet) are excluded to avoid very complicated mapping and still maintaining the loss of information very low and not affecting the quality of the plants observations.

The other columns of the sheet are used in `measurementOfFact`, or `mof` (output file: `./data/processed/mof.csv`) and are mapped as follows.

## `Submers Code`

- `Submers Code`: values are mapped as `measurementValue`, the string `submerged code` is used as `measurementType`
- the combination of `deelmonster_id`, `interval` and the string 'submerged_code' forms the `measurementID`. Examples: `21327837:0-10m:submerged_code`, `21327837:10-20m:submerged_code`.

## `submers`

- `submers`: values are mapped as `measurementValue`, the string `submerged category` is used as `measurementType`
- the combination of `deelmonster_id`, `interval` and the string 'submerged_category' forms the `measurementID`. Examples: `21327837:0-10m:submerged_category`, `21327837:10-20m:submerged_category`.

## `Submers weging`

Not mapped. It can be added of course. Iif mapped, please provide the English translation of it.

## gevalideerd

I am afraid there is no way to add a validation status for a measurement in DwC. Validation refers only to taxonomic identification ([`identificationVerificationStatus`](https://dwc.tdwg.org/terms/#dwc:identificationVerificationStatus)) or georeference verification ([`georeferenceVerificationStatus`](https://dwc.tdwg.org/terms/#dwciri:georeferenceVerificationStatus)).

## opmerking

Mapped to `eventRemarks`. At the moment it is everywhere empty, but in this way it's future proof 😄 

## waterlichaamcategorietype

Not mapped at child event level. This field is a field at parent event level (it's not dependent on `interval` value). At that level, I  use the values from sheet `plaatsen`.

**Comment by peterdesmet** [comment]
@damianooldoni are there every observations linked to deelmonster+interval?

**Comment by damianooldoni** [comment]
Yes, but they are very few:

```r
> features %>%
+   filter(!.data$deelmonster_id %in% vegetations$deelmonster_id) %>%
+   nrow()
filter: removed 4,047 rows (99%), 36 rows remaining
[1] 36
```

**Comment by damianooldoni** [comment]
Maybe it's also important to add that the observations of plants are NEVER linked to these child events! ALL observations are linked to the events  (`deelmonster_id`).

**Comment by peterdesmet** [comment]
Have changed this in #22 so:

- We don't have child events for these intervals
- The intervals (and the abundance of the plants) are coded as measurements
