### ISSUE TITLE
Translate `sliblaag` values 

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#17]
The field name (sliblaag) is translated in EN as `sludge level` and used as `measurementType` in measurementOrFacts (`mof.csv`).`measurementUnit` is set to `cm`. The values in `sliblaag` are mapped  as `measurementValue`. The following translation/mapping has been used:

sliblaag value (NL) | sludge level (EN)
--- | --- 
`< 5 cm slib` | `0-5`
`5 à 20 cm slib` | `5-20`
`> 20 cm slib` | `>20`
`slib afwezig` | `0`
`slib aanwezig maar meting onmogelijk` | `>0`

**To be reviewed by VMM**.

**Comment by peterdesmet** [comment]
Looks good to me.
