### ISSUE TITLE
Adding `samplingProtocol` to all events?

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#20]
**Question to VMM**: is there a sampling protocol which we could refer to?
See definition and examples: https://dwc.tdwg.org/terms/#dwc:samplingProtocol.
A VMM example: in the invertebrates dataset, the samplingProtocol was `Handnet`.

**Comment by damianooldoni** [comment]
The document containing the sampling protocol is in Dutch and we got it by mail.
I have just asked to Maarten if he has a link to such pdf so that we can use it as `samplingProtocol`.
If not, @peterdesmet, can we use just `monitoring` maybe?

**Comment by damianooldoni** [comment]
No URL. Internal document.

**Comment by peterdesmet** [comment]
Set to `transect monitoring` for all.
