### ISSUE TITLE
Mapping `groeivorm`

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#21]
The growth form should be translated to English. Proposal still TO DO.

**Comment by peterdesmet** [comment]
Note that occurrenceRemarks is already used for `eradicated`, `found as tracks`, etc. I would not concatenate these values into that field too. Not sure where to best map it.

**Comment by damianooldoni** [comment]
Can it be that you are confusing the remarks from rattenapp dataset with this dataset? I have no idea which column `eradicated` and `found as tracks` belong to.

**Comment by peterdesmet** [comment]
Indeed, is the other dataset! 😅

**Comment by damianooldoni** [comment]
If not indicated, most of the terms are translated based on [this table](https://academic.oup.com/view-large/83960091), from [this article](https://academic.oup.com/aob/article/109/5/1047/141156?login=false).

`groeivorm` (NL) | growth form (EN translation) | comments
--- | --- | ---
`Vallisneriden` | Vallisneriden | 
`Grote monocotylen` |  Big monocotyledons | not in table. Based on web, e.g. from [Britannica](https://www.britannica.com/plant/monocotyledon)
`Parvopotamiden` | Parvopotamiden  | 
`Pepliden` | Pepliden |
`Lemniden` | Lemniden |
`Ceratophylliden` | Ceratophylliden |
`Elodeïden` | Elodeiden |
`Land` | terrestrial | my translation
`Houtig` | wood | my translation
`Nymphaeïden` | Nymphaeiden |
`Myriophylliden` | Myriophylliden | 
`Hydrochariden` | Hydrochariden | 
`Magnopotamiden` | Magnopotamiden | 
`Onbepaald` | undetermined | 
`Riccielliden` | Riccielliden | 
`Watermossen` | water moss | 
`Chariden` | Hydrochariden | 
`Enteromorpha` | Enteromorpha | https://www.gbif.org/species/2645431
`Stratiotiden` | Stratiotiden | 
`Batrachiiden` | Batrachiden |
`Filamenteuze algen` | Filamentous algae | https://www.sciencedirect.com/topics/immunology-and-microbiology/filamentous-alga
`Isoëtiden` | Isoëtiden | 
`Veenmos` | Sphagnum moss | "Sphagnum moss" is a vernacular name. The scientific name of this genus is `Sphagnum`.

@peterdesmet: can you review this as well and include it in your PR? Thanks.

**Comment by peterdesmet** [comment]
Will do. What about `Oever/moeras`?

**Comment by damianooldoni** [comment]
Oeps, I forgot it. I would say: "shore and marsh plants"

**Comment by peterdesmet** [comment]
Now mapped in 04f2e88
