### ISSUE TITLE
BasisOfRecord not in event core, but in occurrence extension

### ISSUE THREAD

**Issue by LienReyserhove** [riparias/vmm-macrophytes-occurrences#24]
The DwC term `basisOfRecord` is now included in the [event.csv](https://github.com/riparias/vmm-macrophytes-occurrences/blob/main/data/processed/event.csv). This term belongs to the occurrence extension, see [these specifications](https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml). @damianooldoni

**Comment by damianooldoni** [comment]
@peterdesmet, what do you think about it? Based on document pointed by @LienReyserhove I think she is 100% right.

**Comment by damianooldoni** [comment]
Discussed with @peterdesmet. You are right. Thanks for checking. Done by @peterdesmet in  https://github.com/riparias/vmm-macrophytes-occurrences/commit/aa211eaa5523e5cfb9b0c09d82d12eb294c0fc53
