### ISSUE TITLE
Solve duplicates occurrenceID

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#25]
There are 1608 duplicates at occurrence level (`occurrenceID`) due to the observation of the same species with two difference growth form. Good cath @LienReyserhove! The number of duplicates is still low, almost 3,7% of all occurrences. 

My proposed solution: creating hashes based not only on species name but on the combination of species name and growth form.

@LienReyserhove, @peterdesmet: what do you think about it?
Example: 
```r
> vdigest(paste0(observations$`Macrofyt Naam`[1:2],
+                observations$groeivorm[1:2]),
+         algo = "md5")
      Rorippa amphibiaOever/moeras    Sparganium emersumVallisneriden 
"35531b275a90b778df8b789382dfed20" "342e1f2934d6eccb21cf7430c8972bf6"
```

**Comment by damianooldoni** [comment]
The reason behind this strategy instead of pasting the multiple growth form in the `occurrenceRemarks` (e.g. `"growth form: Vallisneriden, Nymphaeiden"`) is that the abundance (Tansley scale values) can be different depending on the combination of growth form and species. Example from two duplicates:

eventID | occurrenceID | organismQuantity | organismQuantityType |  occurrenceRemarks
--- | --- | --- | --- | ---
21345184 | 21345184:c2a4912956dbb824e5bd4542ecb7c348 | s | Tansley vegetation scale | growth form: shore and marsh plants
21345184 | 21345184:c2a4912956dbb824e5bd4542ecb7c348 | f | Tansley vegetation scale | growth form: Vallisneriden

**Comment by peterdesmet** [comment]
What you suggest seems like the best approach, but it is quite subject to change. I don't have a better alternative.

**Comment by damianooldoni** [comment]
Yes, I share your same doubts: if they change the dictionary of growth forms, we will have to deal with all new observations. As long as thei changes are not retroactive we can deal with this. And even if they change growth form values retroactively, we know that the data up to end 2021 should be mapped based on the "old" export, so we filter the "old" data from the new export.

**Comment by damianooldoni** [comment]
@peterdesmet: can you approve the PR https://github.com/riparias/vmm-macrophytes-occurrences/pull/26 then? If you are busy I can merge, I have admin rights.
