### ISSUE TITLE
What to do with species aggregate

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#3]
There are three taxa defined with rank "species aggregate":
1. Callitriche obtusangula/platycarpa (160 observations)
2. Nasturtium officinale/microphyllum (2 observations)
3. Nitella flexilis/opaca (2 observations)

Possible solutions:
1. do not map them
2. include them at genus level (e.g.  "Nitella flexilis/opaca" becomes "Nitella")
3. use the first taxon (e.g. "Nitella flexilis/opaca becomes "Nitella flexilis")

I would not map them as they are because the rank "species aggregate" doesn't exist and the double taxon will never be recognized by the GBIF taxonomic backbone.

**Comment by peterdesmet** [comment]
Please include them and use taxonRank `speciesAggregate` (available on https://rs.gbif.org/vocabulary/gbif/rank_2015-04-24.xml). For waarnemingen.be we use the taxonRank `multispecies` for these, which is not a correct use. I'm curious to see how `speciesAggregate` will be handled by GBIF.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet. However, I cannot find clear instructions on how to write such species. From your link I read:

>  An aggregate may be denoted by a group name interpolated in parentheses.

But I do not understand how to do it.  Something like this?
`Callitriche obtusangula/platycarpa` -> `Callitriche (obtusangula,platycarpa)`

**Comment by peterdesmet** [comment]
I would leave those names as is for now. It's an interesting question on how to write these though (and with what rank), maybe good to ask in GBIF portal-feedback

**Comment by damianooldoni** [comment]
Thanks @peterdesmet. Issue posted: https://github.com/gbif/portal-feedback/issues/4014
