### ISSUE TITLE
Mapping few scientific names and ranks

### ISSUE THREAD

**Issue by damianooldoni** [riparias/vmm-macrophytes-occurrences#6]
`Macrofyt Naam` + `Macrofyt Auteur` | `Macrofyt Rang` | mapped scientificName | mapped taxonRank
--- | --- | --- | ---
Salix cinerea L. (incl. kruisingen) |  `Functional group` | [Salix cinerea L.](https://www.gbif.org/species/5372605) | `species`
Draadwier | `Functional group` | thread algae |  `functional group`
Draadwier (submers) | `Functional group` |  thread algae | `functional group`
Salix fragilis L. (incl. kruisingen) |  `Functional group` | ~[Salix ×fragilis L.](https://www.gbif.org/species/5372829)~ Salix fragilis L. | `species`
Nymphaea spec. (neofyt) | Unnkown | [Nymphaea](https://www.gbif.org/species/2882411) | `genus`
Ranunculus peltatus groep | `Species group` | [Ranunculus peltatus](https://www.gbif.org/species/8365713) **group** | `agg.`
Equisetum x litorale Kühl. ex Rupr. | `Species hybrid` | no changes | `species`
Ranunculus aquatilis groep | `Species group` | [Ranunculus aquatilis](https://www.gbif.org/species/3033464) **group** | `agg.`
Mentha arvensis groep | `Species group` | [Mentha arvensis](https://www.gbif.org/species/2927192) **group** | `agg.`
Ranunculus subg. Batrachium | `Subgenus` | no changes | `subgenus`
Salix spp. (broad leaves) | `Functional group` | [Salix](https://www.gbif.org/species/3039576) | `genus`
Salix spp. (small leaves) | `Functional group` | [Salix](https://www.gbif.org/species/3039576) | `genus`
Galium palustre L. subsp. palustre| `Subspecies` | ~[Galium palustre L.](https://www.gbif.org/species/2913130)~ no changes | `species`
Mentha x villosa Huds. | `Species hybrid` | no changes | `species`
Populus x canadensis Moench | `Species hybrid` | no changes | `species`
Rubus fruticosus groep | `Species groep` | [Rubus fruticosus](https://www.gbif.org/species/8436459) **group** | `agg.`
Taraxacum Wiggers sect. Subvulgaria Christians. | `Section` | ~[Taraxacum F.H.Wigg.](https://www.gbif.org/species/8322495)~ no changes | `genus`
Carduus | `Genus` | no changes | `genus`
Fontinalis | `Genus` | no changes | `genus`
Galeopsis | `Genus` | no changes. Automatically matched to [Galeopsis](https://www.gbif.org/species/8423109) instead of more obscure `genus` [Galeopsis Moench ](https://www.gbif.org/species/7383585) | `genus`
Lysichiton americanus Hultén et St John x L. camtschatcensis (L.) Schott | `Species` | ~[Lysichiton americanus × camtschatcensis](https://www.gbif.org/species/10236166)~ Lysichiton americanus x camtschatcensis | `species`
Salix | `Genus` | no changes | `genus`
Trifolium | `Genus` | no changes. Automatically matched to [Trifolium Tourn. ex L.](https://www.gbif.org/species/2973363) instead of the less common genera [Trifolium Travassos, 1922](https://www.gbif.org/species/3268117) and [Trifolium (Čelak.) Gibelli & Belli, 1891](https://www.gbif.org/species/7804316). | `genus`
Urtica | `Genus` | no changes | `genus`

**Comment by peterdesmet** [comment]
Overall, I would leave the names as is, except when:

- `groep` is mentioned
- something is added between parenthesis

E.g. `Ranunculus subg. Batrachium` and `Galium palustre L. subsp. palustre` are valid names

**Comment by peterdesmet** [comment]
I would also refrain from using `verbatimTaxonRank`.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet for your input! I understand your point. You would like to publish the things with the least changes as possible knowing that not everything will be matched to GBIF. So, if I understood your point of view, I should add `draadwier` as `thread algae` to the output with rank `functional group`, am I right? I will update the table above based on your suggestions then.

**Comment by peterdesmet** [comment]
> should add `draadwier` as `thread algae` to the output with rank `functional group`

Sounds like a good idea.

**Comment by damianooldoni** [comment]
@peterdesmet: last but not least. Some genera would not be matched without autorship due to homonimy, e.g. genus `Carduus` (see table) which could refer to both [Carduus L.](https://www.gbif.org/species/3114511) (plants)  and [Carduus](https://www.gbif.org/species/8158002)  (animals). To solve this, I would like to add the auteurship (see table). Unless GBIF takes the information from field `kingdom` which we populate in `occurrences.csv` to perform the taxonomic match? I don't think so. What do you suggest?

**Comment by peterdesmet** [comment]
GBIF does take the kingdom information into account when doing a match, so no need to add `L.`

**Comment by damianooldoni** [comment]
Mapping of `scientificName` and `taxonRank` added and table above updated to the last changes. @peterdesmet: do you agree on this mapping?

**Comment by peterdesmet** [comment]
I have updated some values in the table, keeping it even closer to the original.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet. Some changes were already implemented in the script but not in the table above. 👍

**Comment by peterdesmet** [comment]
According to https://github.com/gbif/portal-feedback/issues/4014#issuecomment-1095760569 we can leave `group` in the name (translated from `group`) and set the rank marker for those to `agg.`

**Comment by damianooldoni** [comment]
Thanks @peterdesmet. Adapting the mapping based on last version of the table.
